import streamlit as st

st.image('yates_lab.png')
st.title('Yates Lab Applications')


st.subheader("Public")
st.write("FASTA Suite [link](https://pgarrett-scripps-fastasuite-home-v5ftop.streamlitapp.com/)")
st.write("Peptide Modification Visualizer [link](https://pgarrett-scripps-peptidemodificationvis-modification-app-ctqser.streamlitapp.com/)")
st.write("Fragment Ion Visualizer [link](https://pgarrett-scripps-fragmentionvisualizer-main-qbdch1.streamlitapp.com/)")
st.write("Spectral Library Generator [link](https://pgarrett-scripps-peptidemodificati-spectral-library-app-6gepgv.streamlitapp.com/)")
st.write("GlycoMSQuantpy [link](https://pgarrett-scripps-glycomsquantpy-home-3gd96u.streamlitapp.com/)")
st.write("")
st.subheader("Private (Scripps VPN Required)")
st.write("Spectra Suite [link](http://marlin:8504)")
st.write("Fasta Suite [link](http://marlin:8506)")
st.write("IP2 Explorer [link](http://marlin:8507)")
st.write("Raw Extractor [link](http://marlin:8508)")
st.write("GlycoMsQuantpy [link](http://marlin:8509)")
st.write("")
st.subheader("Development Branch")
st.write("GlycoMsQuantpy (dev) [link](http://marlin:8510)")
st.write("Spectra Suite (dev) [link](http://marlin:8505)")
st.write("")
st.write("")
st.write("contact: pgarrett@scripps.edu")
